name: frontend unit test
on:
  push: 
    paths: 
      - "client/**"
      - ".github/workflows/*"
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      newUnityVersion:
        description: 'The new version number string.'
        required: false
jobs:
  frontend_build:
    name: frontend build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build
        uses: docker/build-push-action@v2
        with:
          context: client
          push: false
          tags: hujindi1212/fib-seq-client-unit-test:latest
          file: client/Dockerfile.dev
      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: unit test
        uses: addnab/docker-run-action@v3
        with: 
          image: hujindi1212/fib-seq-client-unit-test:latest
          shell: bash
            run: docker run -e CI=true fib-seq/client-test yarn test --coverage
