name: frontend unit test
on:
  push: 
    paths: 
      - "client/**"
      - ".github/workflows/*"
  pull_request:
    branches:
      - main

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t hujindi1212/fib-seq-client ../../client
