name: server-ci
on:
  push: 
    paths: 
      - "server/**"
      - ".github/workflows/server-ci.yml"
  pull_request:
    branches:
      - main
jobs:
  server_prod_build:
    name: server production build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: build
        uses: docker/build-push-action@v2
        with:
          context: server
          push: true
          tags: hujindi1212/fib-seq-server:latest
          file: server/Dockerfile
      - name: image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
